name: Linux wheel TestPyPI

on: [push]

jobs:
  build_wheel_linux:
    name: Build wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    container: quay.io/pypa/manylinux2014_x86_64:2022-12-11-145d107
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v3

      - name: Build Python wheel
        run: |
          chmod -R +x tools/* \
          && tools/linux-wheels.sh
      - uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: ./wheelhouse

  test_wheel_linux:
    name: Test Python ${{ matrix.python-version }} wheel on Linux
    runs-on: ubuntu-latest
    needs: build_wheel_linux
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: wheels
          path: wheels

      - name: Install deplex package
        env:
          py_version: ${{ matrix.python-version }}
        run: |
          python -m pip install ./wheels/deplex-*-cp${py_version//./}-*-manylinux*.whl

      - name: Install Test requirements
        run: |
          python -m pip install -r python/requirements_test.txt

      - name: Python tests
        run: |
          python -m pytest python