name: MacOS wheel TestPyPI

on: [push]

jobs:
  build_wheel_macos:
    name: Build wheel on MacOS-10.15
    runs-on: macos-10.15
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3

      - name: Build Python wheel
        run: |
          chmod -R +x tools/* \
          && tools/macos-wheels.sh
      - uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: ./build/wheels

  test_wheel_macos:
    name: Test Python ${{ matrix.python-version }} wheel on MacOS
    runs-on: macos-latest
    needs: build_wheel_macos
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.6", "3.7", "3.8", "3.9", "3.10" ]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: wheels
          path: wheels

      - name: Install deplex package
        env:
          py_version: ${{ matrix.python-version }}
        run: |
          python -m pip install ./wheels/deplex-*-cp${py_version//./}-*-macos*.whl

      - name: Install Test requirements
        run: |
          python -m pip install -r python/requirements_test.txt

      - name: Python tests
        run: |
          python -m pytest python