name: unit-tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - stable

jobs:
  gtest:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Build code with CMake
        run: |
          cmake -B ${{ github.workspace }}/build -DBUILD_TESTS=ON
          cmake --build ${{ github.workspace }}/build --config Release

      - name: Run GTest
        run: ctest -C ${{env.BUILD_TYPE}}
        working-directory: ${{ github.workspace }}/build/cpp/tests