name: Cross-platform Python wheels

on: [push, pull_request, workflow_dispatch]

jobs:
  linux_wheel:
    name: Build wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    container: quay.io/pypa/manylinux2014_x86_64:2022-12-11-145d107
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v3

      - name: Build Python wheel
        run: |
          chmod -R +x tools/* \
          && tools/linux-wheels.sh

      - uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: ./wheelhouse


#  macos_wheel:
#    name: Build wheel on ${{ matrix.os }}
#    runs-on: ${{ matrix.os }}
#    strategy:
#      fail-fast: false
#      matrix:
#        os: [ macos-10.15 ]
#    steps:
#      - uses: actions/checkout@v3
#
#      - name: Build Python wheel
#        run: |
#          chmod -R +x tools/* \
#          && tools/macos-wheels.sh
#      - uses: actions/upload-artifact@v3
#        with:
#          name: wheels
#          path: ./wheelhouse
#
#  windows_wheel:
#    name: Build wheel on ${{ matrix.os }} ${{ matrix.arch }} Py-${{ matrix.python-version }}
#    runs-on: ${{ matrix.os }}
#    strategy:
#      fail-fast: false
#      matrix:
#        os: [ windows-2019 ]
#        arch: [ x64 ]
#        python-version: [ "3.6", "3.7", "3.8", "3.9", "3.10" ]
#    steps:
#      - uses: actions/checkout@v3
#
#      - name: Setup Python
#        uses: actions/setup-python@v4
#        with:
#          python-version: ${{ matrix.python-version }}
#
#      - name: Display Python version
#        run: python --version
#
#      - name: Build Python wheel
#        run: ./tools/windows-wheels.cmd
#
#      - uses: actions/upload-artifact@v3
#        with:
#          name: wheels
#          path: ./build/wheels