name: Windows wheel TestPyPI

on: [push]

jobs:
  build_wheel_windows64:
    name: Build wheel on ${{ matrix.os }} ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-2019 ]
        arch: [ x64 ]
        python-version: ['3.9', '3.10']
    steps:
      - uses: actions/checkout@v3
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Display Python version
        run: python --version

      - name: Build Python wheel
        run: ./tools/windows-wheels.cmd

      - uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: ./wheelhouse
